### ISSUE TITLE
code only works for square grids

### ISSUE THREAD

**Issue by McJazzy** [valantonini/AStar#1]
There's a bug in your code. The calculation of a single location value based on x,y is done wrongly.

var newLocation = (newLocationY << _gridYLog2) + newLocationX;

should be

var newLocation = (newLocationY << _gridXLog2) + newLocationX;

etc.

If the matrix is  square, gridYLog2 and gridXlog2 will be equal, and thus the code will work.

**Comment by valantonini** [comment]
This should be fixed now. Thanks for the feedback
