### ISSUE TITLE
Weights are ignored

### ISSUE THREAD

**Issue by fholmqvist** [valantonini/AStar#13]
## Expected

A* algorithm respects weights:
> Given a weighted graph, a source node and a goal node, the algorithm [A*] finds the shortest path (with respect to the given weights) from source to goal.

Given a grid with weighted tiles around walls:
![image](https://github.com/valantonini/AStar/assets/22743750/7c23a901-7cf6-438a-976a-19e03c6f25b8)

An agent should avoid hugging walls.

## Actual

Agent ignores weights (positive or negative) and hugs walls:
![image](https://github.com/valantonini/AStar/assets/22743750/f7346f0c-48a3-4ef8-8604-7aeef8058fd0)

**Comment by valantonini** [comment]
Hi @fholmqvist,

The  implementation never made use of the weights but I think somewhere the code mentions values other than 1 could be used for a weight in the future. It's come up a couple times and I wrote [a short blog post on how you can change 1 line to achieve weighting](https://valantonini.com/posts/20210401/). I believe xpoveda also came to a similar approach[ in a similar issue ](https://github.com/valantonini/AStar/issues/12#issuecomment-2020168648). 

Are you using the source code directly or the nuget package?

**Comment by valantonini** [comment]
Since this has been asked a few times, I have implemented weightings. It can be opted into via options to maintain backwards compatability for those who rely on the current behaviour.

```csharp
var level = @"1111115
              1511151
              1155511
              1111111";
var world = Helper.ConvertStringToPathfinderGrid(level);
var opts = new PathFinderOptions { Weighting = Weighting.Positive };
var pathfinder = new PathFinder(world, opts);
```

[A prerelease of this can be found on Nuget](https://www.nuget.org/packages/AStarLite/1.3.0-beta.1)

**Comment by fholmqvist** [comment]
That made all the difference, I appreciate the nice replies and excellent work. Thank you! :slightly_smiling_face:

**Comment by valantonini** [comment]
you're welcome, thank you for the kind words.
