### ISSUE TITLE
FindPath mismatching x for y? Incorrect path returned

### ISSUE THREAD

**Issue by frankhale** [valantonini/AStar#2]
First of all thank you for this library. It's super simple to use and is exactly what I'm looking for, for my game. However I think I found a bug.

I have a 10x10 grid and I want to find the path from 1,1 to 1,8 (x = 1, y = 1), (x = 1, y = 8) but the path found is not correct in my opinion. 

Here is the code which is based off the code in your tests:

```csharp
var level = @"XXXXXXXXXX
              XOOXOOOOOX
              XOOXOOOOOX
              XOOOOOOOOX
              XXXOOOOOXX
              XOOOOOXOOX
              XOOOOOXOOX
              XOOOOOXOOX
              XOOXOOOOOX
              XXXXXXXXXX";

var _grid = new byte[10, 10];
var splitLevel = level.Split('\n')
                      .Select(x => x.Trim())
                      .ToList();

for (var x = 0; x < splitLevel.Count; x++)
{
    for (var y = 0; y < splitLevel[x].Length; y++)
    {
        if (splitLevel[x][y] != 'X')
        {
            _grid[x, y] = 1;
        }
    }
}

var pathfinder = new PathFinder(_grid, new PathFinderOptions
{                
    Diagonals = false,
    HeavyDiagonals = false
});
var path = pathfinder.FindPath(new Point(1, 1), new Point(1, 8));
Helper.Print(_grid, path);
```

The path found is not expected. The end path node is x = 8, y = 1.

```
0 0 0 0 0 0 0 0 0 0
0 * * 0 1 1 1 1 * 0
0 1 * 0 1 1 1 1 * 0
0 1 * * * * * * * 0
0 0 0 1 1 1 1 1 0 0
0 1 1 1 1 1 0 1 1 0
0 1 1 1 1 1 0 1 1 0
0 1 1 1 1 1 0 1 1 0
0 1 1 0 1 1 1 1 1 0
0 0 0 0 0 0 0 0 0 0
```

Path expected is x = 1, y = 8:

If I reverse the X,Y in the FindPath function I get the results expected:

```csharp
pathfinder.FindPath(new Point(1, 1), new Point(8,1));
```

Expected path:

```
0 0 0 0 0 0 0 0 0 0
0 * 1 0 1 1 1 1 1 0
0 * 1 0 1 1 1 1 1 0
0 * * * 1 1 1 1 1 0
0 0 0 * 1 1 1 1 0 0
0 * * * 1 1 0 1 1 0
0 * 1 1 1 1 0 1 1 0
0 * 1 1 1 1 0 1 1 0
0 * 1 0 1 1 1 1 1 0
0 0 0 0 0 0 0 0 0 0
```

Am I missing something or is x and y reversed in the FindPath function? My thought is that dealing with a 2D array map it should be treated as Y = row, column = X, eg: map[y, x] in C# code.

Here is my mental model of how a grid works in C# as a 2D array where grid rows are Y and grid columns are X (eg. grid[y,x])

![image](https://user-images.githubusercontent.com/190154/108314430-e1ef1d80-7187-11eb-9f9d-91d96a4baa2f.png)

Ref: https://github.com/valantonini/AStar/blob/8adb1a7c7fe830253a989f6b6fcb043ccec1e18f/AStar.Core/PathFinder.cs#L43

I see grid being used like this `_mCalcGrid[start.X, start.Y]` when I think it should be used like `_mCalcGrid[start.Y, start.X]`

There are other references that use it like `grid[x,y]`

Wait, PrintPath is doing what I expect, iterating over rows and columns eg grid[y,x] but your test code is grid[x,y]. The flipping of x and y is totally confusing me. 

```csharp
public static string PrintPath(byte[,] grid, List<PathFinderNode> path)
{
    var s = new StringBuilder();

    for (var row = 0; row < grid.GetLength(0); row++)
    {
        for (var column = 0; column < grid.GetLength(1); column++)
        {
            if (path.Any(n => n.X == row && n.Y == column))
            {
                s.Append("*");
            }
            else
            {
                s.Append(grid[row, column]);
            }
            s.Append(' ');
        }
        s.Append(Environment.NewLine);
    }
    return s.ToString();
}
```

Found it!!! X and Y are backwards here:

![image](https://user-images.githubusercontent.com/190154/108315991-3c897900-718a-11eb-8f9a-4eabc97781da.png)

I am coming off the heels of the Point class defined by Microsoft where X and Y opposite

![image](https://user-images.githubusercontent.com/190154/108316139-778bac80-718a-11eb-961c-ad75d050e2a1.png)

**Comment by frankhale** [comment]
Ref: https://github.com/valantonini/AStar/blob/8adb1a7c7fe830253a989f6b6fcb043ccec1e18f/AStar.Core/PathFinder.cs#L43

I see grid being used like this `_mCalcGrid[start.X, start.Y]` when I think it should be used like _mCalcGrid[start.Y, start.X]`

**Comment by frankhale** [comment]
Wait, PrintPath is doing what I expect, iterating over rows and columns eg grid[y,x] but your test code is grid[x,y]. The flipping of x and y is totally confusing me. 

```csharp
public static string PrintPath(byte[,] grid, List<PathFinderNode> path)
{
    var s = new StringBuilder();

    for (var row = 0; row < grid.GetLength(0); row++)
    {
        for (var column = 0; column < grid.GetLength(1); column++)
        {
            if (path.Any(n => n.X == row && n.Y == column))
            {
                s.Append("*");
            }
            else
            {
                s.Append(grid[row, column]);
            }
            s.Append(' ');
        }
        s.Append(Environment.NewLine);
    }
    return s.ToString();
}
```

**Comment by frankhale** [comment]
Found it!!! X and Y are backwards here:

![image](https://user-images.githubusercontent.com/190154/108315991-3c897900-718a-11eb-8f9a-4eabc97781da.png)

**Comment by frankhale** [comment]
I am coming off the heels of the Point class defined by Microsoft where X and Y opposite

![image](https://user-images.githubusercontent.com/190154/108316139-778bac80-718a-11eb-961c-ad75d050e2a1.png)

**Comment by frankhale** [comment]
Nothing?

**Comment by valantonini** [comment]
Hi Frank,

Apologies for the delay getting back to you.

Technically this wasn't a bug, just a poor design choice on my behalf.

Instead of using a [cartesian co-ordinate system](https://en.m.wikipedia.org/wiki/Cartesian_coordinate_system) denoted by P(x,y) to reference points, I opted to use a [matrix index notation](http://web.mit.edu/course/3/3.11/www/modules/index.pdf) which use P(row, column).

I did this because I had some ideas at the time for some vector maths I wanted to support and I thought this may prevent me having to juggle between the 2 systems.

In hindsight this was probably not a great decision and as you mentioned, by using the Point struct, it had made it all the more confusing.

I'd like to fix this up to work as you would expect however work and family commitments make me unable to commit to a time frame.

Thanks very much for all the feedback and apologies again for the delay.

Val

**Comment by frankhale** [comment]
Thank you for the explanation!!!

**Comment by valantonini** [comment]
Hi @frankhale,

I have rewritten this completely (currently on the [development branch](https://github.com/valantonini/AStar/tree/development) and as a [0.2.x-alpha nuget package](https://www.nuget.org/packages/AStarLite/). There are a lot of breaking changes but there is now the ability to use either Points or Matrix positions to interact with the library as well as much cleaner and efficient code. Please check it out when you have a chance and let me know what you think.

Thanks,

Val

**Comment by frankhale** [comment]
WOW! That is great news. I will definitely check this out. Thank you so much!
